const helpers = [
  {
    id: 1,
    title: 'Professional Electrician',
    imgUrl: 'https://picsum.photos/200/300',
    loc: 'Auckland',
    desc: 'Experienced electrician with a track record of solving complex electrical issues.',
    typeUrl: '/providers',
    category: 'Electrical Services',
  },
  {
    id: 2,
    title: 'Experienced Gardener',
    imgUrl: 'https://picsum.photos/200/300',
    loc: 'Wellington',
    desc: 'Skilled gardener offering landscaping and garden maintenance services.',
    typeUrl: '/providers',
    category: 'Gardening Services',
  },
  {
    id: 3,
    title: 'Professional Mover',
    imgUrl: 'https://picsum.photos/200/300',
    loc: 'Christchurch',
    desc: 'Reliable moving services for both residential and commercial clients.',
    typeUrl: '/providers',
    category: 'Moving Services',
  },
  {
    id: 4,
    title: 'Experienced Painter',
    imgUrl: 'https://picsum.photos/200/300',
    loc: 'Dunedin',
    desc: 'High-quality painting services for homes and businesses.',
    typeUrl: '/providers',
    category: 'Painting Services',
  },
  {
    id: 5,
    title: 'Skilled Handyman',
    imgUrl: 'https://picsum.photos/200/300',
    loc: 'Tauranga',
    desc: 'Versatile handyman offering a wide range of repair and maintenance services.',
    typeUrl: '/providers',
    category: 'Home Repair Services',
  },
  {
    id: 6,
    title: 'Expert Plumber',
    imgUrl: 'https://picsum.photos/200/300',
    loc: 'Hamilton',
    desc: 'Certified plumber with experience in residential and commercial plumbing.',
    typeUrl: '/providers',
    category: 'Plumbing Services',
  },
  {
    id: 7,
    title: 'Professional Electrician',
    imgUrl: 'https://picsum.photos/200/300',
    loc: 'Napier',
    desc: 'Electrical services provider with a focus on safety and efficiency.',
    typeUrl: '/providers',
    category: 'Electrical Services',
  },
  {
    id: 8,
    title: 'Experienced Carpenter',
    imgUrl: 'https://picsum.photos/200/300',
    loc: 'Palmerston North',
    desc: 'Skilled carpenter specializing in custom woodworking and construction.',
    typeUrl: '/providers',
    category: 'Carpentry Services',
  },
  {
    id: 9,
    title: 'Roofing Specialist',
    imgUrl: 'https://picsum.photos/200/300',
    loc: 'New Plymouth',
    desc: 'Roofing expert providing installation and repair services for all types of roofs.',
    typeUrl: '/providers',
    category: 'Roofing Services',
  },
  {
    id: 10,
    title: 'Landscaping Professional',
    imgUrl: 'https://picsum.photos/200/300',
    loc: 'Rotorua',
    desc: 'Landscaping and garden design services for residential and commercial properties.',
    typeUrl: '/providers',
    category: 'Landscaping Services',
  },
  {
    id: 11,
    title: 'HVAC Specialist',
    imgUrl: 'https://picsum.photos/200/300',
    loc: 'Nelson',
    desc: 'Heating, ventilation, and air conditioning services for homes and businesses.',
    typeUrl: '/providers',
    category: 'HVAC Services',
  },
  {
    id: 12,
    title: 'Expert Mason',
    imgUrl: 'https://picsum.photos/200/300',
    loc: 'Invercargill',
    desc: 'Experienced mason specializing in stone and brickwork for architectural projects.',
    typeUrl: '/providers',
    category: 'Masonry Services',
  },
  {
    id: 13,
    title: 'Flooring Specialist',
    imgUrl: 'https://picsum.photos/200/300',
    loc: 'Queenstown',
    desc: 'Flooring installation and repair services for residential and commercial properties.',
    typeUrl: '/providers',
    category: 'Flooring Services',
  },
  {
    id: 14,
    title: 'Security Expert',
    imgUrl: 'https://picsum.photos/200/300',
    loc: 'Gisborne',
    desc: 'Security services provider offering surveillance and access control solutions.',
    typeUrl: '/providers',
    category: 'Security Services',
  },
  {
    id: 15,
    title: 'Appliance Repair Specialist',
    imgUrl: 'https://picsum.photos/200/300',
    loc: 'Hastings',
    desc: 'Appliance repair services for a wide range of household appliances.',
    typeUrl: '/providers',
    category: 'Appliance Repair',
  },
  {
    id: 16,
    title: 'Demolition Specialist',
    imgUrl: 'https://picsum.photos/200/300',
    loc: 'Timaru',
    desc: 'Demolition services for residential and commercial structures.',
    typeUrl: '/providers',
    category: 'Demolition Services',
  },
  {
    id: 17,
    title: 'Pool Maintenance Expert',
    imgUrl: 'https://picsum.photos/200/300',
    loc: 'Napier',
    desc: 'Pool maintenance and cleaning services for residential and commercial pools.',
    typeUrl: '/providers',
    category: 'Pool Services',
  },
  {
    id: 18,
    title: 'Land Surveyor',
    imgUrl: 'https://picsum.photos/200/300',
    loc: 'Dunedin',
    desc: 'Land surveying and mapping services for property development projects.',
    typeUrl: '/providers',
    category: 'Surveying Services',
  },
  {
    id: 19,
    title: 'Interior Designer',
    imgUrl: 'https://picsum.photos/200/300',
    loc: 'Rotorua',
    desc: 'Interior design and decorating services for homes and commercial spaces.',
    typeUrl: '/providers',
    category: 'Interior Design',
  },
  {
    id: 20,
    title: 'Window Installation Specialist',
    imgUrl: 'https://picsum.photos/200/300',
    loc: 'Palmerston North',
    desc: 'Window installation and repair services for residential and commercial properties.',
    typeUrl: '/providers',
    category: 'Window Services',
  },
];

export default helpers;
